import type { Metadata } from "next"
import { Inter } from 'next/font/google'
import "./globals.css"
import Sidebar from "@/devComponents/sidebar/Sidebar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "---ABC-->",
  description: "Generated by Joe",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-screen">
          
            <main className="flex-1 w-full">
              {children}
            </main>
            
        </div>
      </body>
    </html>
  )
}